### ISSUE TITLE
react-native 版本0.46.1 扫码很慢啊...有时扫不错要么得1分钟左右才能扫出来  求解

### ISSUE THREAD

**Issue by isszz** [MarnoDev/AC-QRCode-RN#14]
RT

**Comment by isszz** [comment]
测试手机是小米4  安卓版本是6.01 @MarnoDev

**Comment by MarnoDev** [comment]
我升级到 0.47 也没有出现扫码很慢的问题，也用小米 5s 测试过，都可以正常扫码。有没有相应的日志，可以贴一下

**Comment by isszz** [comment]
@MarnoDev 这个是react-native-camera使用的ZXing的扫码问题,我试过一个老的扫码组件集成的也是旧的ZXing就正常,但是最新的这个ZXing就很慢

**Comment by MarnoDev** [comment]
恩，看下能不能优化下

**Comment by Adar-Li** [comment]
@isszz 扫描慢的问题您解决了吗？

**Comment by fenglu09** [comment]
目前同样碰到Android扫码慢的问题，请问解决了吗？ @isszz

**Comment by isszz** [comment]
@fenglu09 @Adar-Li 已经换了一个组件虽然有点旧作者也没维护,但是稍微修改下是可以正常运行,扫码也是相对较快的
https://github.com/react-native-component/react-native-smart-barcode
有能力的希望可以基于这个组件fork继续维护下去

**Comment by fenglu09** [comment]
@isszz  我也换的这个组件，感觉速度还行，而且不会出现像框外还能扫码的情况

**Comment by Adar-Li** [comment]
@isszz 谢谢 您能加我下微信吗？方便沟通下，13361027656
