### ISSUE TITLE
undefine is not an object evaluating 'CameraManager.Aspect'

### ISSUE THREAD

**Issue by huyifan** [MarnoDev/AC-QRCode-RN#16]
![image](https://user-images.githubusercontent.com/5880447/30331060-5caab59a-9809-11e7-903c-66afc90616f7.png)

为什么会报这个错误呀？

**Comment by huyifan** [comment]
奇怪自己倒腾了一下反而倒腾出来了
![image](https://user-images.githubusercontent.com/5880447/30331678-09f2b224-980b-11e7-8709-c29df9f6923e.png)
![image](https://user-images.githubusercontent.com/5880447/30331686-0e6ecc2a-980b-11e7-9d60-3712e6040306.png)

就是在终端输入了
npm install react-native-camera --save
react-native link react-native-camera

**Comment by vonch** [comment]
我也遇到大坑了，跟你一样。居然整个项目都运行不起来了。

**Comment by 1525685999** [comment]
npm install react-native-camera --save
react-native link react-native-camera 
导入之后项目运行不起来了

**Comment by yxwandroid** [comment]
同上 遇到这个问题

**Comment by yxwandroid** [comment]
npm install react-native-camera --save
react-native link react-native-camera
导入之后项目运行不起来了

出现   
undefined is not an object (evaluating _react2.PropTypes.oneofType)

**Comment by tianweicc** [comment]
@huyifan 装了另外一个组件之后 你就可以用了？  我按照它的文档 只要一引入 马上挂不能跑 你有没有遇到

**Comment by tianweicc** [comment]
@yxwandroid 哥们 解决了没

**Comment by vonch** [comment]
解决啦，哈哈~~~

**Comment by tianweicc** [comment]
@vonch 你怎么解决的 可以贴一下么

**Comment by yxwandroid** [comment]
@tianweicc 没有解决 我换的另外的一个      比这个快  http://www.jianshu.com/p/b46328ba1b33

**Comment by yxwandroid** [comment]
如果作者还是没解决大家可以使用这个    http://www.jianshu.com/p/b46328ba1b33

**Comment by tianweicc** [comment]
@yxwandroid   这个集成进去 0.50不能用  你有遇到么

**Comment by yxwandroid** [comment]
@tianweicc    http://www.jianshu.com/p/b46328ba1b33 你用这个  这个亲测能用的我昨天刚集成进去

**Comment by tianweicc** [comment]
@yxwandroid ok 我再试试 方便加个qq么  昨天我集成试过 是有遇到问题  等下遇到问一下你可以吧  648338679

**Comment by yxwandroid** [comment]
@tianweicc   我 qq1396781292

**Comment by donglyu** [comment]
0.48之后, 要在其源码里面从import PropTypes from 'React' 改成 import PropTypes from 'prop-types';
且 从React.ProTypes.... 改成ProTypes, 去掉React

**Comment by hishamreactz** [comment]
fix this.
