### ISSUE TITLE
安装时提示UNMET PEER DEPENDENCY react@>=15.4.0

### ISSUE THREAD

**Issue by ShawnDeveloper** [MarnoDev/AC-QRCode-RN#17]
我的项目的react版本是16.0.0-alpha.12，但是通过npm安装的时候提示需要react@>=15.4.0：

UNMET PEER DEPENDENCY react@>=15.4.0

npm WARN react-native-camera@0.7.0 requires a peer of react@>=15.4.0 but none was installed.

**Comment by 1525685999** [comment]
楼主 解决了吗？我也遇到同样的问题了

**Comment by mySteamIDisLiKang** [comment]
这个可以直接无视
