### ISSUE TITLE
大bug，扫描退出后无法执行InteractionManager.runAfterInteractions

### ISSUE THREAD

**Issue by yeatsYz** [MarnoDev/AC-QRCode-RN#19]
从扫描页面退出后，如果下一个页面有调用InteractionManager.runAfterInteractions方法，会由于扫描组件内的动画一直循环而无法执行，只需要在添加isInteraction: false即可，希望作者可以加一下
scannerLineMove() {
        this.state.animatedValue.setValue(0);  //重置Rotate动画值为0
        Animated.timing(this.state.animatedValue, {
            toValue: this.props.rectHeight,
            duration: this.props.scanBarAnimateTime,
            easing: Easing.linear,
            isInteraction: false
        }).start(() => this.scannerLineMove());
    }

**Comment by Geek-ch** [comment]
我也遇到这个bug了，按1楼的方法是可以的
