### ISSUE TITLE
扫码时，很容易识别扫码框以外的二维码 

### ISSUE THREAD

**Issue by fenglu09** [MarnoDev/AC-QRCode-RN#21]
RT，扫码的时候，可以识别，而且速度很快，但是如果一个单子上面有两个二维码，很容易就误识别了。
经常会识别扫码框以外的二维码，但是并不是自己想要扫的，这样体验很不好

**Comment by Developer45** [comment]
我也遇到类似的问题，在遮罩区域对准二维码扫描，也可以识别，这样就不对了啊，那还画那个框框干什么！！！

**Comment by fenglu09** [comment]
是啊，这样用户体验太差了，最好能够只是别框内的二维码

**Comment by fenglu09** [comment]
@MarnoDev  请问这个能解决吗

**Comment by mrarronz** [comment]
看来作者目前并没有好的解决方案，demo应该也没有再继续维护了。这个问题其实就是要限制二维码的识别区域，只能在框内进行扫描识别。iOS原生使用AVFoundation来实现，有个属性叫做rectOfInterest，是需要计算的，安卓原生应该也一样，我认为最好的解决方案还是用原生实现，然后创建module类导出给RN使用

**Comment by fenglu09** [comment]
原生实现肯定是最好的，主要是对android和iOS都不算太熟。
你有兴趣做一个吗？ @mrarronz

**Comment by mrarronz** [comment]
很久没做安卓了，已经忘得差不多了，需要点时间研究下。iOS原生可以参考我的[QRCodeScanner](https://github.com/mrarronz/QRCodeScanner)

**Comment by zhenizhui** [comment]
目前react-native-camera都没有好的实现，所以暂时是没有的了 😢

**Comment by zhenizhui** [comment]
或者可以试一下这个仓库 https://github.com/shifeng1993/react-native-qr-scanner

它提供了限定区域的扫码

**Comment by fenglu09** [comment]
@zhenizhui  谢谢啦。 已换成了`react-native-smart-barcode`。

**Comment by zhenizhui** [comment]
@fenglu09 你用的RN什么版本的？我用的53.3。感觉你推荐的这个不合适，作者好久没更新了 😢

**Comment by fenglu09** [comment]
我用的`0.48.3`, Fork 自己修改一下就可以用了。

**Comment by zhenizhui** [comment]
关于扫码识别到别的二维码的问题，这里有相关的讨论。

https://github.com/shifeng1993/react-native-qr-scanner/issues/8
