### ISSUE TITLE
Cannot read property 'oneOfType' of undefined

### ISSUE THREAD

**Issue by YeomanYe** [MarnoDev/AC-QRCode-RN#26]
启动报错，怀疑依赖没有更新到最新版本

错误堆栈如下:
Cannot read property 'oneOfType' of undefined
<unknown>
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\ac-qrcode\node_modules\react-native-camera\index.js:75:22
loadModuleImplementation
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:191:4
guardedLoadModule
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:138:11
_require
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:118:2
<unknown>
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\ac-qrcode\QRScanner.js:7
loadModuleImplementation
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:191:4
guardedLoadModule
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:138:11
_require
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:118:2
<unknown>
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\ac-qrcode\index.js:7
loadModuleImplementation
    C:\Users\yeming\Desktop\RN\mcloud-h5\node_modules\metro-bundler\src\Resolver\polyfills\require.js:191:4

**Comment by ghost** [comment]
最新版RN需要单独引入prop-types组件

**Comment by YeomanYe** [comment]
@hiteamLiuLiXue  好的问题解决了

**Comment by YeomanYe** [comment]
@hiteamLiuLiXue 单独引入是指在项目中增加prop-types依赖吗？
我使用npm install prop-types --save之后还是报相同的错

**Comment by qq912276337** [comment]
import PropTypes from 'prop-types';

**Comment by YeomanYe** [comment]
@qq912276337 在使用的地方导入了之后仍然不可用

    import React, {
      Component
    } from 'react';
    import {
      Text,
      Alert,
      View
    } from 'react-native';
    import PropTypes from 'prop-types';
    import { QRScannerView } from 'ac-qrcode';

    export default class DefaultScreen extends Component {
        render() {
            return (

                <QRScannerView
                    onScanResultReceived={this.barcodeReceived.bind(this)}

                    renderTopBarView={() => this.renderTitleBar()}

                    renderBottomMenuView={() => this.renderMenu()}
                />
            )
        }

        renderTitleBar(){
            return(
                <Text
                    style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
                >Here is title bar</Text>
            );
        }

        renderMenu() {
            return (
                <Text
                    style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
                >Here is bottom menu</Text>
            )
        }

        barcodeReceived(e) {
            Alert.alert('Type: ' + e.type + '\nData: ' + e.data);
            //console.log(e)
        }
    }

**Comment by zhang-kui** [comment]
遮罩层会把顶部和底部的视图区域也遮罩住？这样的话就没有办法点击事件，请问怎么处理啊？

**Comment by YeomanYe** [comment]
@zhang-kui 我觉得你提个issue会比较好，在这里提没什么人会看见

**Comment by qq912276337** [comment]
我也怀疑 是依赖问题。下载demo可以运行 我升级到react-native 版本最新就爆类似错误

**Comment by YeomanYe** [comment]
@qq912276337 那你问题解决了吗？我在android上能用，在ios上一运行就直接退出

**Comment by qq912276337** [comment]
ios- 项目名称-info.plist 打开该文件。增加一个键值对
键：Privacy - Camera Usage Description 
值：是否允许此App使用你的相机？
@YeomanYe

**Comment by ghost** [comment]
@YeomanYe  单独引入以后需要在index.js文件的340多行的地方进行一些修改，就是React.PropTypes改成PropTypes,你可以看pull Request我提过的请求，如果你是要使用扫描功能那么我有更好的推荐

**Comment by YeomanYe** [comment]
@hiteamLiuLiXue 我想使用扫描二维码获取信息的功能，要兼容android和ios的

**Comment by hiteamLiuLiXue** [comment]
@YeomanYe  我们目前用的是基于react-native-smart-barcode这个，但是这个也不支持新版本了，我自己又改了改发了个新的hiteam-rn-qrcode，你可以试试，安卓文档你可以参考我github上的dev分支的说明https://github.com/hiteamLiuLiXue/hiteam-rn-qrcode/tree/dev，ios文档就参考原插件的就行

**Comment by hiteamLiuLiXue** [comment]
@YeomanYe我们目前用的是基于react-native-smart-barcode这个，但是这个也不支持新版本了，我自己又改了改发了个新的hiteam-rn-qrcode，你可以试试，安卓文档你可以参考我github上的dev分支的说明，ios文档就参考原插件的就行。https://github.com/hiteamLiuLiXue/hiteam-rn-qrcode/tree/dev，

**Comment by YeomanYe** [comment]
@qq912276337 改过，仍旧不行

**Comment by YeomanYe** [comment]
@hiteamLiuLiXue 哇，厉害了。我会试试的，十分感谢

**Comment by anchoretics** [comment]
@hiteamLiuLiXue 我也只想扫描二维码，你说有更好的推荐，是什么呀，能实现微信那样的吗

**Comment by caohongtao** [comment]
@hiteamLiuLiXue @YeomanYe 推荐的哪个？能否在这里发一下，我也想试试。

**Comment by shaoting0730** [comment]
@YeomanYe  这个错误怎么改啊?

**Comment by jasonzhangdong** [comment]
> @qq912276337 在使用的地方导入了之后仍然不可用
> 
> ```
> import React, {
>   Component
> } from 'react';
> import {
>   Text,
>   Alert,
>   View
> } from 'react-native';
> import PropTypes from 'prop-types';
> import { QRScannerView } from 'ac-qrcode';
> 
> export default class DefaultScreen extends Component {
>     render() {
>         return (
> 
>             <QRScannerView
>                 onScanResultReceived={this.barcodeReceived.bind(this)}
> 
>                 renderTopBarView={() => this.renderTitleBar()}
> 
>                 renderBottomMenuView={() => this.renderMenu()}
>             />
>         )
>     }
> 
>     renderTitleBar(){
>         return(
>             <Text
>                 style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
>             >Here is title bar</Text>
>         );
>     }
> 
>     renderMenu() {
>         return (
>             <Text
>                 style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
>             >Here is bottom menu</Text>
>         )
>     }
> 
>     barcodeReceived(e) {
>         Alert.alert('Type: ' + e.type + '\nData: ' + e.data);
>         //console.log(e)
>     }
> }
> ```

不是这样改的，请看最上面第一个YeomanYe的修改

**Comment by jasonzhangdong** [comment]
> @qq912276337 在使用的地方导入了之后仍然不可用
> 
> ```
> import React, {
>   Component
> } from 'react';
> import {
>   Text,
>   Alert,
>   View
> } from 'react-native';
> import PropTypes from 'prop-types';
> import { QRScannerView } from 'ac-qrcode';
> 
> export default class DefaultScreen extends Component {
>     render() {
>         return (
> 
>             <QRScannerView
>                 onScanResultReceived={this.barcodeReceived.bind(this)}
> 
>                 renderTopBarView={() => this.renderTitleBar()}
> 
>                 renderBottomMenuView={() => this.renderMenu()}
>             />
>         )
>     }
> 
>     renderTitleBar(){
>         return(
>             <Text
>                 style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
>             >Here is title bar</Text>
>         );
>     }
> 
>     renderMenu() {
>         return (
>             <Text
>                 style={{color:'white',textAlignVertical:'center', textAlign:'center',font:20,padding:12}}
>             >Here is bottom menu</Text>
>         )
>     }
> 
>     barcodeReceived(e) {
>         Alert.alert('Type: ' + e.type + '\nData: ' + e.data);
>         //console.log(e)
>     }
> }
> ```

你改错地方了
