### ISSUE TITLE
cannot read property 'Aspect' of undefined

### ISSUE THREAD

**Issue by qq912276337** [MarnoDev/AC-QRCode-RN#27]

**Comment by hphpwj** [comment]
me too, help!

**Comment by Herryjoeson** [comment]
求解决

**Comment by hphpwj** [comment]
感觉好像是react-native-camera最近版本有问题，换一个以前的版本就行

**Comment by yexiaosong** [comment]
我解决了这个问题，是因为权限问题，我的发生在ios版本中，在目录`ios/你的项目名/info.plist`的xml中的dict项中添加权限
`<key>WorkspacePath</key>
<string>/Users/yexiaosong/develop/friday/ios/friday.xcodeproj</string>`。如果还不行，就直接下载react-native-camera并link，同时添加权限。

**Comment by pheromone** [comment]
@yexiaosong 权限指的相机权限? <key>WorkspacePath</key> <string>/Users/yexiaosong/develop/friday/ios/friday.xcodeproj</string>你这是指的什么?

**Comment by SSShooter** [comment]
> 感觉好像是react-native-camera最近版本有问题，换一个以前的版本就行

换了哪个版本？

**Comment by hphpwj** [comment]
"react-native-camera": "0.12.0",
半年多前用的，现在不知道还行不

**Comment by SSShooter** [comment]
> "react-native-camera": "0.12.0",
> 半年多前用的，现在不知道还行不

谢谢
