### ISSUE TITLE
Undefined is not an object (Evaluating 'CameraManager.Aspect')

### ISSUE THREAD

**Issue by rexlow** [MarnoDev/AC-QRCode-RN#3]
Installed the module and tried to link, the link command does not do anything.

So I went further and check my MainApplication.java and the module object does not exist in the java file.

Any resolution?

RN version - 0.41.2

**Comment by jqn** [comment]
Make sure you have react-native-camera install and that your packager is not running while installing. Checkout this issue https://github.com/lwansbrough/react-native-camera/issues/528

**Comment by MarnoDev** [comment]
`run react-native link react-native-camera `

**Comment by rexlow** [comment]
Please update your readme file, it did not include the step to install react-native-camera module

**Comment by Josema** [comment]
Having the same issue. Tried `react-native link` and `react-native link react-native-camera`

Versions:
```
  "dependencies": {
    "ac-qrcode": "^1.0.1",
    "expo": "^17.0.0",
    "react": "16.0.0-alpha.6",
    "react-native": "^0.44.3",
    "react-native-camera": "^0.9.4",
    "react-native-qrcode": "^0.2.3",
    "react-native-vector-icons": "^4.2.0",
    "react-primitives": "^0.4.2",
    "styled-components": "^2.1.0"
  },
```

Maybe for react 16-alpha?
