### ISSUE TITLE
求解：部分安卓机，扫描界面会有一条线

### ISSUE THREAD

**Issue by t407289575** [MarnoDev/AC-QRCode-RN#31]
![0115343708766lhm](https://user-images.githubusercontent.com/7932453/33594213-fae459a4-d9cd-11e7-82b7-e7ef390fc35a.png)

**Comment by xiaodiqaq** [comment]
同求，是否解决？

**Comment by xiaodiqaq** [comment]
我线条出现的原因好像是因为header头部的关系，把它放在 renderTopBarView就好了

**Comment by vivikenen** [comment]
重新调`QRScanner.js` 里的style

在 `measureTotalSize` function里set一个height的值
```
measureTotalSize(e) {
    const totalSize = e.layout;
    this.setState({
      topWidth: totalSize.width,
      height: totalSize.height,
    })
  }
```

然后在  `getTopMaskHeight() ` function 里，把
```
    return this.state.topHeight + this.props.rectHeight;
```
改成
```
    return this.state.height - this.state.topHeight;
```
