### ISSUE TITLE
Old version being added in node modules

### ISSUE THREAD

**Issue by TayyabSuhail123** [MarnoDev/AC-QRCode-RN#43]
When I install this module using NPM, an older version is added to my node modules that uses React.PropTypes in QRscanner.js and uses react-native-camera version 0.7.0 which crashes

**Comment by Abdullah-7** [comment]
Yes, this is annoying :(

**Comment by hugomosh** [comment]
How do you solve it?

**Comment by FJB-ZA** [comment]
+1 on this, anyone found any solutions on how to fix this?
