### ISSUE TITLE
react-native-camera 扫码二维码一直扫不出内容，onBarCodeRead 就是不调用

### ISSUE THREAD

**Issue by wangliguang** [MarnoDev/AC-QRCode-RN#5]
# 机型
    魅族 pro6
# android版本
    6.0 

# React-Native版本
   0.43.2
# 问题
没有报错，就是用摄像头扫描二维码时，扫不出来结果，onBarCodeRead不调用

**Comment by JusticeLai** [comment]
魅族note5 乐视 都不行..只有华为荣耀8的可以..

**Comment by MarnoDev** [comment]
我手上的几个安卓手机：小米5s，oppoR9，锤子M1，vivoX7，华为都可以。目前手上没有魅族手机，暂时没法测试了，主要不报错，很难定位问题了。有没有日志可以贴一下，或者你直接用 `react-native-camera` 试下可以扫码不？
