### ISSUE TITLE
在努比亚手机，Android 4.4.2版本上使用该组件，扫描特别不灵敏，有时候甚至不起作用。

### ISSUE THREAD

**Issue by Ariel08081214** [MarnoDev/AC-QRCode-RN#6]
在6.0上是正常的，很快就能识别出来。
react-native 0.40

**Comment by MarnoDev** [comment]
扫码灵敏行应该是和相机有关系的，和代码实现应该无关

**Comment by MarnoDev** [comment]
扫码灵敏行应该是和相机有关系的，和代码实现应该无关

**Comment by MarnoDev** [comment]
直接使用 react-native-camera 扫码试下呢？扫不出来的时候有没有输出什么日志？
