### ISSUE TITLE
demo 可以运行，只不过扫描的时候出现了空白的情况。

### ISSUE THREAD

**Issue by Dan-0216** [MarnoDev/AC-QRCode-RN#64]
1.查看了应用的权限相机的权限是开启的。
2.demo运行起来扫码的页面扫描的内容为空白，不是摄像头的实时画面。如何解决？

**Comment by Star-Sky-Star** [comment]
你解决了吗

**Comment by Dan-0216** [comment]
> 你解决了吗

我这边已经可以正常运行了

**Comment by guo519300884** [comment]
朋友,怎么解决的,求分享一下呀

**Comment by guo519300884** [comment]
> > 你解决了吗
> 
> 我这边已经可以正常运行了

求分享一波呀 朋友

**Comment by Dan-0216** [comment]
> > > 你解决了吗
> > 
> > 
> > 我这边已经可以正常运行了
> 
> 求分享一波呀 朋友

这个我好久之前解决的，记得当时是换了个安卓的手机试试 还是开启权限之类的

**Comment by Dan-0216** [comment]
总而言之 感觉兼容性不是太好
