### ISSUE TITLE
Readme文档代码错误

### ISSUE THREAD

**Issue by xjy0925** [MarnoDev/AC-QRCode-RN#67]
import **QRScannerView** from 'react-native-qrcode-**sanner**-view';
应该改为 import **{QRScannerView}** from 'react-native-qrcode-**scanner**-view';

**Comment by evan0204** [comment]
> QRScannerView

我就踩到这个坑了，谢了

**Comment by jmy10241024** [comment]
这个真坑

**Comment by MarnoDev** [comment]
抱歉，已修复
